Repository ROCm/HIPIFY, pull requests merged in 2020-09, with the labels that each got.

#181 [HIPIFY] Added directory and file exclusion, updated whitelist
  src/CUDA2HIP_Perl.cpp
Labels: feature

#182 [HIPIFY] Sync with #181
  bin/hipify-perl
Labels: perl, sync

#183 [HIPIFY] CUDA Runtime API: add Versions: A|D|R
  bin/hipify-perl
  src/CUDA2HIP_Runtime_API_functions.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: feature

#184 [HIPIFY][#172] Initial documentation auto-generation
  src/ArgParse.cpp
  src/ArgParse.h
  src/CUDA2HIP.h
  src/CUDA2HIP_Doc.cpp
  src/CUDA2HIP_SPARSE_API_functions.cpp
  src/CUDA2HIP_Scripting.h
  src/main.cpp
Labels: feature

#185 [HIPIFY][#172] Markdown docs generation is implemented
  src/CUDA2HIP.cpp
  src/CUDA2HIP.h
  src/CUDA2HIP_Doc.cpp
  src/Statistics.cpp
Labels: feature

#186 [HIPIFY][#172][fix] Do not print HIP API name if it's unsupported
  src/CUDA2HIP_Doc.cpp
Labels: fix

#187 [HIPIFY][#172] CUDA Runtime API Types versioning
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_functions.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
  src/CUDA2HIP_SPARSE_API_functions.cpp
  src/CUDA2HIP_SPARSE_API_types.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: enhancement, feature, fix

#188 [HIPIFY][#172] CUDA Driver API functions versioning
  src/CUDA2HIP_Driver_API_functions.cpp
Labels: feature

#189 [HIPIFY] Fix Linux build
  src/CUDA2HIP_Doc.cpp
Labels: fix

#190 [HIPIFY][doc] Update README.md
  README.md
Labels: documentation

#191 [HIPIFY][WIN] Fix some D9002 and D9025 warnings
  CMakeLists.txt
  src/CUDA2HIP_Driver_API_types.cpp
Labels: build, fix

#192 [HIPIFY][#172] Add footnotes to all generated docs
  src/CUDA2HIP_Doc.cpp
Labels: enhancement
