Repository ROCm/HIPIFY, pull requests merged in 2020-05, with the labels that each got.

#108 [HIPIFY][SPARSE] Final sync with hipSPARSE (#108)
  bin/hipify-perl
  src/CUDA2HIP_SPARSE_API_functions.cpp
  tests/unit_tests/libraries/cuSPARSE/cuSPARSE_12.cu
Labels: SPARSE, perl, sync, test

#109 Removing packaging with HIP; HIPIFY is not a part of HIP anymore
  packaging/hipify-clang.txt
Labels: build, fix

#110 Remove hipify-clang pkg CUDA install dependency
  packaging/hipify-clang.txt
Labels: build, fix

#112 [HIPIFY][doc] Update README.md
  README.md
Labels: documentation

#113 [HIPIFY][#111] Teach HIPIFY to warn about deprecated CUDA APIs
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Driver_API_types.cpp
  src/HipifyAction.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: feature

#114 [HIPIFY][#111] Mark all CUDA Runtime API deprecated identifiers
  src/CUDA2HIP_Runtime_API_functions.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
Labels: feature

#115 [HIPIFY][doc] Update README.md: LLVM 10.0.1-rc1 - the latest supported LLVM Release
  README.md
Labels: documentation

#117 [HIPIFY][#111] Teach hipify-perl to warn about deprecated CUDA APIs
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
  tests/unit_tests/libraries/cuRAND/benchmark_curand_kernel.cpp
Labels: feature, perl

#116 [HIPIFY] Set configurable install path
  CMakeLists.txt
  packaging/hipify-clang.txt
Labels: build, enhancement

#119 [HIPIFY][fix] Explicit #include <system_error> for std::error_code
  src/StringUtils.h
Labels: fix

#120 [HIPIFY][fix] Remove unsupported CUDA API from a cuRAND test
  tests/unit_tests/libraries/cuRAND/benchmark_curand_kernel.cpp
Labels: fix

#121 [HIPIFY][cmake] Minor simplifications
  CMakeLists.txt
Labels: enhancement
