Repository ROCm/HIPIFY, pull requests merged in 2020-10, with the labels that each got.

#193 [HIPIFY][#172] CUDA Driver API Data Types versioning (Part 2)
  bin/hipify-perl
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
Labels: enhancement, fix

#194 [HIPIFY][#172] CUDA Driver API Data Types versioning (Part 3 of 3)
  bin/hipify-perl
  src/CUDA2HIP_Driver_API_types.cpp
Labels: enhancement, fix

#195 [HIPIFY][#172][BLAS] cuBLAS API functions versioning
  bin/hipify-perl
  src/CUDA2HIP_BLAS_API_functions.cpp
Labels: BLAS, documentation, enhancement

#196 [HIPIFY][#172][BLAS] cuBLAS API Data types versioning
  src/CUDA2HIP_BLAS_API_types.cpp
Labels: BLAS, documentation, enhancement

#197 [HIPIFY][#172][RAND] cuRAND API versioning
  src/CUDA2HIP_RAND_API_functions.cpp
Labels: RAND, documentation, enhancement

#198 [HIPIFY][#172][FFT] cuFFT API functions versioning
  src/CUDA2HIP_FFT_API_functions.cpp
Labels: FFT, documentation, enhancement

#199 [HIPIFY][#172][RAND] cuRAND API Data Types versioning
  src/CUDA2HIP_RAND_API_types.cpp
Labels: RAND, documentation, enhancement

#200 [HIPIFY][#172][FFT] cuFFT API Data Types versioning
  bin/hipify-perl
  src/CUDA2HIP_FFT_API_types.cpp
Labels: FFT, documentation, enhancement

#201 [HIPIFY][doc] LLVM 11.0.0 is the latest stable release
  README.md
Labels: documentation

#203 [HIPIFY] CUDA 11.1 Driver API Functions support
  bin/hipify-perl
  src/CUDA2HIP_Driver_API_functions.cpp
Labels: feature

#204 [HIPIFY] CUDA 11.1 Runtime API Functions support
  bin/hipify-perl
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Runtime_API_functions.cpp
Labels: feature

#206 [HIPIFY][#178][patch] Add patches for clang 10.0.0, 10.0.1, and 11.0.0
  README.md
  patches/patch_for_clang_10.0.0_bug_47332.zip
  patches/patch_for_clang_10.0.1_bug_47332.zip
  patches/patch_for_clang_11.0.0_bug_47332.zip
Labels: documentation, fix

#207 [HIPIFY][doc] Update README.md
  README.md
Labels: documentation

#205 [HIPIFY] Fixed Subdirectory Exclusion
  src/CUDA2HIP_Perl.cpp
Labels: fix

#208 [HIPIFY][doc] Update README.md: mention how to generate CUDA2HIP documentation
  README.md
Labels: documentation

#209 [HIPIFY][perl] Formatting
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
Labels: enhancement

#210 [HIPIFY][perl] Update hipify-perl only
  bin/hipify-perl
Labels: enhancement

#211 [HIPIFY][doc] README.md update
  README.md
Labels: documentation

#212 [HIPIFY][compatibility] LLVM 12.0.0 compatibility support
  src/HipifyAction.cpp
  src/LLVMCompat.cpp
  src/LLVMCompat.h
Labels: clang, compatibility

#213 [HIPIFY] CUDA 11.1 Runtime API Data Types support
  bin/hipify-perl
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
Labels: feature
