Repository ROCm/HIPIFY, pull requests merged in 2020-07, with the labels that each got.

#144 [HIPIFY][doc] README.md update
  README.md
Labels: documentation

#146 Fix folder exclusion with hip path.
  packaging/hipify-clang.txt
Labels: fix, package

#145 [HIPIFY] CUDA 11.0 Runtime API data types support
  bin/hipify-perl
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
Labels: NVIDIA, sync

#147 [HIPIFY][doc] Update README.md: Remove HIP legacy text
  README.md
Labels: documentation

#148 [HIPIFY] CUDA 11.0 Runtime API functions support
  bin/hipify-perl
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Runtime_API_functions.cpp
Labels: NVIDIA, sync

#149 [HIPIFY] cuBLAS 11.0 API support
  bin/hipify-perl
  src/CUDA2HIP_BLAS_API_functions.cpp
  src/CUDA2HIP_BLAS_API_types.cpp
Labels: BLAS, sync

#150 [HIPIFY][BLAS] Add a support for vector and matrix async functions
  bin/hipify-perl
  src/CUDA2HIP_BLAS_API_functions.cpp
Labels: BLAS, sync

#152 [HIPIFY][BLAS] Adding gemm_ex batched functions
  bin/hipify-perl
  src/CUDA2HIP_BLAS_API_functions.cpp
Labels: BLAS, sync

#153 [HIPIFY][BLAS] Sync with state-of-the-art rocBLAS and hipBLAS libraries
  bin/hipify-perl
  src/CUDA2HIP_BLAS_API_functions.cpp
Labels: BLAS, sync

#151 [HIPIFY][package] Set packaging arch, field separators
  CMakeLists.txt
  packaging/cpack_project_config.txt
  packaging/hipify-clang.txt
Labels: fix, package

#155 [HIPIFY][doc] Update Readme.md (versioning)
  README.md
Labels: documentation

#156 [HIPIFY][doc] LLVM 10.0.1 - the latest supported LLVM release
  README.md
Labels: documentation

#157 [HIPIFY][#88] Compilation Database support via "-p" option and "compile_commands.json" file
  .gitignore
  src/main.cpp
  tests/lit.cfg
  tests/run_test.bat
  tests/unit_tests/compilation_database/cd_intro.cu
  tests/unit_tests/compilation_database/compile_commands.json.in
  tests/unit_tests/compilation_database/include/inc.h
Labels: feature, test

#158 [HIPIFY][test][linux] Test infrastructure for '-p' option
  tests/run_test.sh
Labels: feature, test

#159 [HIPIFY][doc][#88] JSON Compilation Databases are supported now
  README.md
Labels: documentation

#160 [HIPIFY][build] Update CMakeLists.txt
  CMakeLists.txt
Labels: build

#161 [HIPIFY][doc] Update README.md: LLVM 11.0.0-rc1 - the latest supported LLVM Release
  README.md
Labels: documentation

#162 [HIPIFY][doc] Shorten README.md
  README.md
Labels: documentation, enhancement

#163 [HIPIFY] cuRAND 11.0 API support
  bin/hipify-perl
  src/CUDA2HIP_RAND_API_types.cpp
Labels: NVIDIA, RAND, sync
