Repository ROCm/HIPIFY, pull requests merged in 2021-12, with the labels that each got.

#467 [HIPIFY][doc] Update building instructions
  README.md
Labels: documentation, fix

#468 [HIPIFY][doc] Add LICENSE.txt file
  LICENSE.txt
Labels: documentation

#469 [HIPIFY][RAND] cuRAND 11.5.1 API support
  bin/hipify-perl
  doc/markdown/CURAND_API_supported_by_HIP.md
  src/CUDA2HIP_RAND_API_functions.cpp
  src/CUDA2HIP_RAND_API_types.cpp
Labels: feature

#470 [HIPIFY][SPARSE] cuSPARSE 11.5.1 API support
  bin/hipify-perl
  doc/markdown/CUSPARSE_API_supported_by_HIP.md
  src/CUDA2HIP_SPARSE_API_functions.cpp
  src/CUDA2HIP_SPARSE_API_types.cpp
Labels: sync, SPARSE

#471 [HIPIFY][doc] CUDA 11.5.1 is the latest supported release
  README.md
Labels: documentation

#472 [HIPIFY] Reintroduce HIPIFY_INSTALL_PATH for CPack
  CMakeLists.txt
Labels: fix, package

#474 [HIPIFY][#456][fix] Fix hipify-perl header replacement
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
Labels: fix

#475 [HIPIFY][#473] Option `--cuda-kernel-execution-syntax` introducing
  src/ArgParse.cpp
  src/ArgParse.h
  src/HipifyAction.cpp
Labels: feature

#476 [HIPIFY] Sync with the upcoming HIP-rocm-5.0.0 - Part 1
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
  src/Statistics.cpp
  src/Statistics.h
  tests/unit_tests/synthetic/driver_enums.cu
  tests/unit_tests/synthetic/driver_functions.cu
Labels: HIP, sync

#477 [HIPIFY] Sync with the upcoming HIP-rocm-5.0.0 - Part 2
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_functions.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
  tests/unit_tests/synthetic/driver_functions.cu
Labels: HIP, sync

#478 [HIPIFY] Sync with the upcoming HIP-rocm-5.0.0 - Part 3
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_functions.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
  tests/unit_tests/synthetic/driver_enums.cu
  tests/unit_tests/synthetic/driver_functions.cu
  tests/unit_tests/synthetic/runtime_enums.cu
Labels: HIP, sync

#479 [HIPIFY] Sync with the upcoming HIP-rocm-5.0.0 - Part 4
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Runtime_API_functions.cpp
  tests/unit_tests/synthetic/driver_functions.cu
Labels: HIP, sync
