Repository ROCm/HIPIFY, pull requests merged in 2021-05, with the labels that each got.

#325 [HIPIFY][DNN] cuDNN 8.2.0 API data types support
  bin/hipify-perl
  doc/markdown/CUDNN_API_supported_by_HIP.md
  src/CUDA2HIP_DNN_API_types.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: DNN, sync

#326 [HIPIFY][DNN] cuDNN 8.2.0 API functions support
  bin/hipify-perl
  doc/markdown/CUDNN_API_supported_by_HIP.md
  src/CUDA2HIP_DNN_API_functions.cpp
Labels: DNN, sync

#327 [HIPIFY][fix] Fix building by old C++ compilers
  src/Statistics.h
Labels: fix

#331 [HIPIFY][SPARSE] Sync with hipSPARSE 4.2.0 (functions)
  bin/hipify-perl
  doc/markdown/CUSPARSE_API_supported_by_HIP.md
  src/CUDA2HIP_SPARSE_API_functions.cpp
  src/CUDA2HIP_SPARSE_API_types.cpp
Labels: SPARSE, sync

#332 [HIPIFY] Sync with HIP-rocm-4.2.0
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
Labels: sync

#315 [HIPIFY] Address sanitizer support
  CMakeLists.txt
  README.md
Labels: build

#333 [HIPIFY] Get rid of building configs with -std=c++11
  CMakeLists.txt
  README.md
  src/main.cpp
Labels: build, enhancement

#335 [HIPIFY][SPARSE] Sync with cuSparse 11.3.1
  bin/hipify-perl
  doc/markdown/CUSPARSE_API_supported_by_HIP.md
  src/CUDA2HIP_SPARSE_API_functions.cpp
  src/CUDA2HIP_SPARSE_API_types.cpp
Labels: SPARSE, sync

#336 [HIPIFY][tests][win] Workaround for VS 16.10
  tests/run_test.bat
Labels: fix
