Repository ROCm/HIPIFY, pull requests merged in 2022-11, with the labels that each got.

#678 [HIPIFY][build][SWDEV-364233] Wrong runpath in hipify-clang
  CMakeLists.txt
Labels: fix, build

#680 [HIPIFY][#584][DNN][MIOpen] cuDNN -> MIOpen - Part 1
  src/CUDA2HIP.cpp
  src/CUDA2HIP_DNN_API_types.cpp
  src/Statistics.cpp
  tests/unit_tests/synthetic/libraries/cudnn2miopen.cu
Labels: test, feature, sync, DNN, MIOpen

#681 [HIPIFY][doc] LLVM 15.0.4 is the latest supported LLVM release
  README.md
Labels: documentation

#682 [HIPIFY][rocBLAS][#SWDEV-365549] Sync with rocBLAS - functions only - Part 1
  bin/hipify-perl
  src/CUDA2HIP_BLAS_API_functions.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: fix, sync, BLAS

#683 [HIPIFY][rocBLAS] Sync with rocBLAS - functions only - Part 2
  src/CUDA2HIP_BLAS_API_functions.cpp
Labels: sync, rocBLAS

#684 [HIPIFY][rocBLAS][fix] Sync with rocBLAS - functions only - Part 3
  bin/hipify-perl
  src/CUDA2HIP_BLAS_API_functions.cpp
Labels: fix, sync, rocBLAS

#685 [HIPIFY][rocBLAS][fix] Sync with rocBLAS - functions only - Part 4
  bin/hipify-perl
  src/CUDA2HIP_BLAS_API_functions.cpp
Labels: fix, sync, rocBLAS

#686 [HIPIFY][rocBLAS][fix] Sync with rocBLAS - functions only - Part 5 - final
  bin/hipify-perl
  src/CUDA2HIP_BLAS_API_functions.cpp
Labels: fix, sync, rocBLAS

#688 [HIPIFY][rocBLAS][fix] Sync with rocBLAS - data types only - Part 1
  src/CUDA2HIP_BLAS_API_types.cpp
Labels: sync, rocBLAS

#687 [HIPIFY][perl] Typos fix
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
Labels: fix, perl

#689 [HIPIFY][#584][DNN][MIOpen] cuDNN -> MIOpen - Part 2
  src/CUDA2HIP_DNN_API_functions.cpp
  src/CUDA2HIP_DNN_API_types.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
  src/HipifyAction.cpp
  src/Statistics.cpp
  tests/unit_tests/synthetic/libraries/cudnn2miopen.cu
Labels: feature, DNN, MIOpen

#691 [HIPIFY][#584][DNN][MIOpen] cuDNN -> MIOpen - Part 3
  src/CUDA2HIP_DNN_API_types.cpp
  tests/unit_tests/synthetic/libraries/cudnn2miopen.cu
Labels: feature, DNN, MIOpen

#690 [HIPIFY][SWDEV-310152][package][build][fix] Remove rpath from binary files
  CMakeLists.txt
Labels: fix, build, package

#692 [HIPIFY][rocBLAS][fix] Sync with rocBLAS - data types only - Part 2 - final
  src/CUDA2HIP_BLAS_API_types.cpp
  src/CUDA2HIP_Complex_API_types.cpp
  src/Statistics.cpp
Labels: sync, rocBLAS

#694 [HIPIFY][#584][DNN][MIOpen] cuDNN -> MIOpen - Part 4
  src/CUDA2HIP_DNN_API_types.cpp
  tests/unit_tests/synthetic/libraries/cudnn2miopen.cu
Labels: feature, sync, DNN, MIOpen

#695 [HIPIFY][doc] LLVM 15.0.5 is the latest supported LLVM release
  README.md
Labels: documentation

#696 [HIPIFY][doc][win] Update README.md
  README.md
Labels: documentation

#697 [HIPIFY][#584][DNN][MIOpen] cuDNN -> MIOpen - Part 5
  src/CUDA2HIP_DNN_API_functions.cpp
  src/CUDA2HIP_DNN_API_types.cpp
  tests/unit_tests/synthetic/libraries/cudnn2miopen.cu
Labels: feature, DNN, MIOpen

#698 [HIPIFY][#584][DNN][MIOpen] cuDNN -> MIOpen - Part 6
  src/CUDA2HIP_DNN_API_functions.cpp
  src/CUDA2HIP_DNN_API_types.cpp
  tests/unit_tests/synthetic/libraries/cudnn2miopen.cu
Labels: feature, sync, DNN, MIOpen

#699 [HIPIFY][#643][rocBLAS][test] Synthetic tests for full coverage of cuBLAS APIs supported by rocBLAS - Part 1
  tests/unit_tests/synthetic/libraries/cublas2rocblas.cu
Labels: test, feature, BLAS, rocBLAS

#700 [HIPIFY][#643][rocBLAS][test] Synthetic tests for full coverage of cuBLAS APIs supported by rocBLAS - Part 2
  src/ArgParse.cpp
  src/ArgParse.h
  src/CUDA2HIP_Runtime_API_types.cpp
  src/Statistics.cpp
  src/Statistics.h
  tests/run_test.bat
  tests/run_test.sh
  tests/unit_tests/synthetic/libraries/cublas2rocblas.cu
  tests/unit_tests/synthetic/libraries/cudnn2miopen.cu
Labels: test, fix, feature, BLAS, rocBLAS

#701 [HIPIFY][doc] LLVM 15.0.6 is the latest supported LLVM release
  README.md
Labels: documentation, clang
