Repository ROCm/HIPIFY, pull requests merged in 2022-01, with the labels that each got.

#480 [HIPIFY][fix] Mark all OCML_BASIC_ROUNDED_OPERATIONS as unsupported
  bin/hipify-perl
  doc/markdown/CUDA_Device_API_supported_by_HIP.md
  src/CUDA2HIP_Device_functions.cpp
Labels: fix

#481 [HIPIFY][fix] Add missing device double functions:
  bin/hipify-perl
  doc/markdown/CUDA_Device_API_supported_by_HIP.md
  src/CUDA2HIP_Device_functions.cpp
Labels: fix

#483 [HIPIFY] Add yet another function support with the argument removal
  src/HipifyAction.cpp
  tests/unit_tests/synthetic/driver_functions.cu
Labels: feature

#484 [HIPIFY] Add support for CUDA 11.6 Driver API data types only
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_types.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: sync, CUDA

#485 [HIPIFY][tests][fix][Linux] Fix failure in driver_functions.cu due to CUDA's `cuuint64_t`
  tests/unit_tests/synthetic/driver_functions.cu
Labels: test, fix

#487 [HIPIFY][SWDEV-316762][fix] Soft link to /opt/rocm/bin is missed for hipify-perl
  CMakeLists.txt
  packaging/hipify-clang.postinst
  packaging/hipify-clang.prerm
  packaging/hipify-clang.rpm_post
  packaging/hipify-clang.rpm_postun
  packaging/hipify-clang.txt
Labels: fix, package

#488 [HIPIFY] Add support for CUDA 11.6 Driver API functions only
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_functions.cpp
Labels: sync, CUDA

#490 [HIPIFY] Install LICENSE.txt file with the package
  LICENSE.txt
  packaging/hipify-clang.txt
Labels: package

#489 [HIPIFY][fix] Remove the absolute paths in post install scripts
  CMakeLists.txt
  packaging/hipify-clang.postinst
  packaging/hipify-clang.prerm
  packaging/hipify-clang.rpm_post
  packaging/hipify-clang.rpm_postun
Labels: fix, package

#492 [HIPIFY] Add support for CUDA 11.6 Runtime API functions only
  bin/hipify-perl
  doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
Labels: sync, CUDA

#493 [HIPIFY][doc] Update README.md
  README.md
Labels: documentation

#495 [HIPIFY][#482][perl] Implement arg removal from a function call in the hipify-perl generation too
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
Labels: feature, perl
