Repository ROCm/HIPIFY, pull requests merged in 2022-04, with the labels that each got.

#522 [HIPIFY][SPARSE] Sync with hipSPARSE 5.1
  bin/hipify-perl
  doc/markdown/CUSPARSE_API_supported_by_HIP.md
  src/CUDA2HIP_SPARSE_API_functions.cpp
Labels: HIP, sync, SPARSE

#512 [HIPIFY][build] File Reorganization with backward compatibility
  CMakeLists.txt
  hipify-backward-compat.cmake
  packaging/hipify-clang.txt
Labels: feature, build, package

#524 [HIPIFY][build] Removed post install and uninstall script
  CMakeLists.txt
  packaging/hipify-clang.txt
Labels: enhancement, fix, package

#526 [HIPIFY][#525][perl] Populate `convertedTags` pattern with libraries' prefixes
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
Labels: fix

#527 [HIPIFY][#525][perl] Fix `CONVERTED refs by names` per file and in total
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
Labels: enhancement, fix, perl

#529 [HIPIFY][#525][perl] Redesign substitution mechanism and statistics output
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
Labels: fix, feature, perl

#530 [HIPIFY][SWDEV-291455][#528] File reorganization
  src/main.cpp
Labels: feature, HIP

#528 [HIPIFY][build]File reorganization changes
  bin/hipconvertinplace-perl.sh
  bin/hipconvertinplace.sh
  bin/hipexamine-perl.sh
  bin/hipexamine.sh
  hipify-backward-compat.cmake
  packaging/hipify-clang.txt
Labels: build, package

#531 [HIPIFY][compatibility][fix] LLVM 15.0.0git compatibility support
  src/HipifyAction.cpp
Labels: fix, clang

#534 [HIPIFY][#533] Fix `hipify-perl` substitution bug
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
Labels: fix, perl

#532 [HIPIFY][#531][SWDEV_331863][temporary][workaround] Add a workaround for the `SWDEV_331863` blocker
  CMakeLists.txt
  src/HipifyAction.cpp
Labels: clang, build, compatibility, temporary

#535 [HIPIFY] README.md update: `LLVM 14.0.3` and `CUDA 11.6.2` are the latest supported releases
  README.md
Labels: documentation
