Repository ROCm/HIPIFY, pull requests merged in 2022-06, with the labels that each got.

#561 [HIPIFY][tests][fix] Synthetic test for CUDA Runtime API functions - Part 2
  tests/unit_tests/synthetic/runtime_functions.cu
Labels: test

#563 [HIPIFY][SWDEV-321112] - Use GNUInstallDirs
  CMakeLists.txt
  hipify-backward-compat.cmake
  packaging/hipify-clang.txt
Labels: build, package

#564 [HIPIFY][tests] Synthetic test for CUDA Runtime API functions - Part 3
  tests/unit_tests/synthetic/runtime_functions.cu
Labels: test

#565 [HIPIFY][tests] Synthetic test for CUDA Runtime API functions - Part 4
  tests/unit_tests/synthetic/runtime_functions.cu
Labels: test

#567 [HIPIFY][perl][#498][#501][fix] Add anchoring for the compared functions to make sure that an entire function name is actually matched
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
Labels: fix, perl

#568 [HIPIFY][doc] LLVM 14.0.5 is the latest supported LLVM release
  README.md
Labels: documentation

#569 [HIPIFY][fix] Fix `cleanupHipifyOptions` function
  src/main.cpp
Labels: fix

#570 [HIPIFY] Introduce `--hip-kernel-execution-syntax` option in `hipify-clang`
  src/ArgParse.cpp
  src/ArgParse.h
  src/HipifyAction.cpp
  tests/unit_tests/options/kernel-execution-syntax/both-kernel-execution-syntax.cu
  tests/unit_tests/options/kernel-execution-syntax/cuda-kernel-execution-syntax.cu
  tests/unit_tests/options/kernel-execution-syntax/hip-kernel-execution-syntax.cu
  tests/unit_tests/options/kernel-execution-syntax/none-kernel-execution-syntax.cu
Labels: feature

#572 [HIPIFY][tests][fix] Pass `hipify-clang` specific options to tests with JSON Compilation Database
  tests/run_test.bat
  tests/run_test.sh
  tests/unit_tests/compilation_database/cd_intro.cu
Labels: test, fix

#573 [HIPIFY][fix] Add missing `hipify-clang` options for `cleanupHipifyOptions` function
  src/main.cpp
Labels: fix

#574 [HIPIFY][refactor] Refactor `cleanupHipifyOptions` function more
  src/ArgParse.cpp
  src/ArgParse.h
  src/main.cpp
Labels: enhancement

#576 [HIPIFY][tests] Synthetic test for CUDA Runtime API functions - Part 5
  src/HipifyAction.cpp
  tests/unit_tests/synthetic/runtime_functions.cu
Labels: test, fix

#577 [HIPIFY][fix] Get rid of `reinterpret_cast` for hipified function arguments
  bin/hipify-perl
  src/CUDA2HIP_Perl.cpp
  src/HipifyAction.cpp
  tests/unit_tests/casts/reinterpret_cast.cu
  tests/unit_tests/synthetic/runtime_functions.cu
Labels: fix

#578 [HIPIFY][fix] Add missing functions that need `HIP_SYMBOL()` macros for their arguments after hipification
  src/HipifyAction.cpp
Labels: fix

#579 [HIPIFY][tests] Synthetic test for CUDA Runtime API functions - Part 6
  tests/unit_tests/synthetic/runtime_functions.cu
Labels: test

#580 [HIPIFY][doc] LLVM 14.0.6 is the latest supported LLVM release
  README.md
Labels: documentation

#583 [HIPIFY][SPARSE] Sync with hipSPARSE 5.2.0
  bin/hipify-perl
  doc/markdown/CUSPARSE_API_supported_by_HIP.md
  src/CUDA2HIP_SPARSE_API_functions.cpp
Labels: HIP, sync, SPARSE
