Repository ROCm/HIPIFY, pull requests merged in 2023-03, with the labels that each got.

#791 [HIPIFY] Sync with CUDA 12.1 - Part 1 - Driver API - types only
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_types.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: sync, CUDA

#792 [HIPIFY][fix] Sync with CUDA 12.1 - Part 2 - Driver API - functions only
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_functions.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: fix, sync, CUDA

#793 [HIPIFY][fix][doc] Sync with CUDA 12.1 - Part 3 - Runtime API - refactor API sections
  bin/hipify-perl
  doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Runtime_API_functions.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
Labels: documentation, fix, sync, CUDA

#794 [HIPIFY][refactor] Introduce `CUDA_DRIVER_API_SECTIONS` enum for Driver API sections
  src/CUDA2HIP.h
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Driver_API_types.cpp
Labels: refactor

#795 [HIPIFY][refactor][fix] Introduce `CUDA_RUNTIME_API_SECTIONS` enum for Runtime API sections
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  src/CUDA2HIP.h
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_functions.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: fix, refactor

#796 [HIPIFY][fix] Sync with CUDA 12.1 - Part 4 - Runtime API
  bin/hipify-perl
  doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_functions.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: sync, CUDA

#797 [HIPIFY][RTC][doc] Sync with CUDA 12.1 - Part 5 - final
  README.md
  bin/hipify-perl
  doc/markdown/CUDA_RTC_API_supported_by_HIP.md
  src/CUDA2HIP_RTC_API_types.cpp
Labels: documentation, sync, CUDA, RTC

#798 [HIPIFY][DNN][doc] cuDNN 8.8.0 is the latest supported cuDNN
  README.md
Labels: documentation, DNN

#799 [HIPIFY] Introduced the option `--default-preprocessor` synonymous with the '--skip-excluded-preprocessor-conditional-blocks' option
  src/ArgParse.cpp
  src/ArgParse.h
  src/LLVMCompat.cpp
Labels: enhancement

#800 [HIPIFY] Revise and fix descriptions of HIPIFY options
  src/ArgParse.cpp
Labels: enhancement, fix

#802 [HIPIFY][#801][SWDEV-343109] Add an explicit `reinterpret_cast` for every `MemberExpr` of the `half2` struct - Step 1
  src/HipifyAction.cpp
  src/HipifyAction.h
  tests/unit_tests/samples/half2_allocators.cu
Labels: feature

#803 [HIPIFY][#801][SWDEV-343109] Add an explicit `reinterpretcast` for e…very `MemberExpr` of the `half2` struct - Step 2
  src/HipifyAction.cpp
  tests/unit_tests/samples/half2_allocators.cu
Labels: feature

#804 [HIPIFY][#801][SWDEV-343109] Add an explicit `reinterpret_cast` for every `MemberExpr` of the `half2` struct - Step 3
  src/HipifyAction.cpp
Labels: feature

#805 [HIPIFY] Introduced the `--versions` option for 3rd-party software
  src/ArgParse.cpp
  src/ArgParse.h
  src/Statistics.h
  src/main.cpp
Labels: feature

#807 [HIPIFY][doc] README.md update - versioning, tests
  README.md
Labels: documentation

#808 [HIPIFY][#801] Introduced the `--no-warnings-on-undocumented-features` option (`false` by default)
  src/ArgParse.cpp
  src/ArgParse.h
  src/HipifyAction.cpp
Labels: feature

#810 [HIPIFY][HIP][5.6.0] Sync - Part 1
  bin/hipify-perl
  doc/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  doc/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  src/CUDA2HIP_Device_functions.cpp
  src/CUDA2HIP_Driver_API_functions.cpp
  src/CUDA2HIP_Driver_API_types.cpp
  src/CUDA2HIP_Runtime_API_functions.cpp
  src/CUDA2HIP_Runtime_API_types.cpp
  src/Statistics.cpp
  src/Statistics.h
Labels: HIP, sync

#811 [HIPIFY][doc] `LLVM 16.0.0` and `CUDA 12.1.0` are the latest supported releases
  README.md
Labels: documentation

#812 [HIPIFY][doc] `README.md` update
  README.md
Labels: documentation

#813 [HIPIFY][SWDEV-376358][doc] Added `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation

#814 [HIPIFY][SWDEV-368821][install][fix] Add `bin` subfolder to installation destination in `CMakeLists.txt`
  CMakeLists.txt
Labels: fix, build, package

#816 [HIPIFY][SWDEV-390802][build][fix] Hipify scripts and binary path updated in hipify-clang.txt
  CMakeLists.txt
  packaging/hipify-clang.txt
Labels: fix, build, package

#818 [HIPIFY][SWDEV-376358][doc] Updated `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation

#819 [HIPIFY][SWDEV-376358][doc] Updated `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation

#820 [HIPIFY][#584][DNN][MIOpen] cuDNN -> MIOpen - Part 7
  src/CUDA2HIP_DNN_API_functions.cpp
  src/CUDA2HIP_DNN_API_types.cpp
  tests/unit_tests/synthetic/libraries/cudnn2miopen.cu
Labels: feature, sync, MIOpen
